### ISSUE TITLE
Create a docker-compose run a Postgresql database with docker

### ISSUE THREAD

**Issue by reaper** [djulai/djulai-com#2]
`docker-compose.yml`

```
version: '3.4'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'djulai'
      POSTGRES_PASSWORD: 'djulai'
```
